/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.asestatuas.golfstrokes;

public class GolfGame {

    public static void main(String[] args) {
        System.out.println("OK");
    }

    /*
     * 
     */
}
